#!/usr/bin/env bash
#Script that displays information about a pages sub-domains.

domain_info () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_info "$1" "www"
  domain_info "$1" "lb-01"
  domain_info "$1" "web-01"
  domain_info "$1" "web-02"
